hypothesis/viahtml

- .gitignore
- Makefile
A place holder for changes required to get the app to deploy. This currently only actually removes a dodgy reference to old via. We don't keep the static directory in the same place.
> Get Viahtml ready for deployment

- bin/build_static.py
Previously this was doing something very weird and getting the parent
directory instead of the project directory.
> Set the target directory for static content correctly

- .coveragerc
- conf/development.ini
- conf/production.ini
- requirements-test.in
- tests/functional/conftest.py
- tests/functional/fixups_test.py
- tests/functional/proxy_test.py
- tests/functional/pywb_config_test.py
- tests/simple_server.py
- tests/unit/conftest.py
- tests/unit/viahtml/app_test.py
- tests/unit/viahtml/hooks_test.py
- tests/unit/viahtml/wsgi_test.py
- tox.ini
- viahtml/app.py
- viahtml/templates/error.html
- viahtml/templates/index.html
- viahtml/templates/query.html
- viahtml/templates/search.html
- viahtml/wsgi.py
There were a number of problems getting this done:
* A lot of how this works is bound up in patching `pywb`
* I can't really think of a non functional way to test most of this
* `pywb` somehow breaks coverage reports... I don't know how but it's weird
* The app you start starts another in a separate process, so you can't patch things
So the approach has been to:
* Unit test what we can
* Functionally test the rest
* Expand the coverage report to span both sets of tests
* Liberally apply `pragma: no cover` to things which clearly should be covered by running the tests
* Run a small, but real web server in a separate process to have something reliable to call
As an interesting aside, because the functional tests make more extensive use of session scoped fixtures, they are actually much …
> Get test coverage to 100%

- tests/functional/conftest.py
- tests/unit/viahtml/app_test.py
- tests/unit/viahtml/wsgi_test.py
- viahtml/app.py
- viahtml/wsgi.py
For whatever mysterious reason, this caused the gevent monkey patching
to kick in at a different time when importing the FrontEndApp, which
makes me think we don't need it...
This is to set us up for the header blocking PR: https://github.com/hypothesis/viahtml/pull/4. We're going to need to modify the headers on the way in and out. This means we need to _be_ the app, rather than just have one.
> Make the application be the WSGI app instead of create one

- tests/functional/conftest.py
- tests/functional/headers_test.py
- tests/simple_server.py
- tests/unit/viahtml/app_test.py
- tests/unit/viahtml/hooks/_headers_test.py
- viahtml/hooks/_headers.py
If the cache is marked public and has a max-age below the minimum of
Cloudflare we flip it to private.
> Proxy the upstream cache control header with translation

- tests/functional/proxy_test.py
- tests/unit/viahtml/hooks/hooks_test.py
- viahtml/hooks/hooks.py
- viahtml/templates/banner.html
This allows you to set an option and have links open in a new tab. For: https://github.com/hypothesis/via3/issues/259
Negative case:
* `make dev`
* Visit: http://localhost:9085/proxy/http://example.com/
* Click on the link
* The link should open in this tab
Positive case:
* `make dev`
* Visit: http://localhost:9085/proxy/http://example.com/?via.external_link_mode=new-tab
* Click on the link
* It should open in a new tab
* Click on a link in that tab
* Links should stay within the same page
> Add external_link_mode option to open links in a new tab

- Dockerfile
- Makefile
- requirements.in
- requirements.txt
This unfortunately leaves whitenoise installed, but hey ho.
It turns out we don't use `make docker` when making the docker image for deployment here: https://github.com/hypothesis/pipeline-library/blob/master/vars/buildApp.groovy
This means the changes to fix it that were made locally don't apply. We have to build inside the docker image instead.
> Build the static items directly in the docker image

- tests/unit/viahtml/hooks/_headers_test.py
- viahtml/hooks/_headers.py
We had a ticket to block infrastructure headers and blocked those we'd seen explicitly. Turns out there are many more returned in different sitautions. It's easier and quicker to block them all in one go.
This came up as a result of being able to check the behavior in live.
> Turns out there are millions of pywb headers, block them all

- tests/unit/viahtml/app_test.py
- tests/unit/viahtml/views/blocklist_test.py
- tests/unit/viahtml/views/status_test.py
- tox.ini
- viahtml/app.py
- viahtml/views/blocklist.py
- viahtml/views/status.py
In preparation for adding a third view some patterns have emerged:
* All the views want to know what the path is
* Not all of the views return something "truthy" when replying
The new path for the landing page will issue a redirect, which won't have any body
> Support "views" with no body and pass in the path

- tests/conftest.py
- tests/functional/conftest.py
- tests/unit/conftest.py
Previously we had two (diverging) copies of the same logic. This makes it easier to add new things to it.
This _isn't_ a pytest fixture, as it's needed in a session scoped fixtured for the functional tests and a per test fixture in the other. I was a bit concerned that tests could mess with it and have cross contamination.
> Share environment variables between tests and functests

- README.md
- conf/development.ini
- tests/conftest.py
- tests/functional/pywb_config_test.py
- tests/functional/viahtml/views/routing_test.py
- tests/unit/viahtml/views/routing_test.py
- viahtml/app.py
- viahtml/blocklist.py
- viahtml/views/routing.py
For https://github.com/hypothesis/via3/issues/285
This adds a landing page for ViaHTML. This works by:
* ~Having static HTML content served from root~
* ~That content redirects to `/route/?url=`~
* ~We have a "view" that catches this, reads the env var `VIA_ROUTING_HOST` and redirects there~
* ~This will be Via 3 for now~
~This means the host can change via ENV var, but we can still serve the same static HTML content.~
Sean correctly pointed out this is dumb. How this now works:
* If you go to "/" this is picked up by a view
* This reads the env var `VIA_ROUTING_HOST` and redirects to the root there
* Run via, via3 and viahtml with `make dev`
* Goto: http://localhost:9085 (viahtml)
* You should end up redirected to Via 3 on http://localhost:9083 and see the landing page
> Add a landing page

- bin/report_metrics.py
- conf/development.ini
- conf/newrelic.ini
- conf/production.ini
- conf/supervisord-dev.conf
- conf/supervisord.conf
- requirements-dev.in
- requirements-test.in
- tests/unit/viahtml/stats_test.json
- tests/unit/viahtml/stats_test.py
- tox.ini
- viahtml/stats.py
How does this work?
* uWSGI can be configured to expose a JSON stats end-point (https://uwsgi-docs.readthedocs.io/en/latest/StatsServer.html)
* This has been configured to port 3033 (I tried a file socket, but it's no quicker and more annoying)
* We run a script which periodically reads from this
* This converts the various values into the format New Relic expects and sends it on it's way
* This is run as a separate process by `supervisord`
* You need your own New Relic account (which you probably have by default)
* Get your license and run `export NEW_RELIC_LICENSE_KEY=<...>`
* `make dev`
* You should eventually see some stats go into New Relic
* A lot of this PR is:
* A config file generated by New Relic
* A big fixture example of uWSGI output
* The approach here is basically the same …
> Report detailed stats from uWSGI to New Relic

- Makefile
This is to make it more convenient to check the image more like we deploy it. This makes writing and testing the dockerfile and setup easier.
> Add a run-docker command to make it easier to test the container image

- conf/supervisord.conf
Previously we were getting:
```
2020-10-30 13:42:52,622 INFO spawned: 'report_metrics' with pid 73
report_metrics (stderr) | Traceback (most recent call last):
report_metrics (stderr) |   File "bin/report_metrics.py", line 10, in <module>
report_metrics (stderr) |     from viahtml.stats import UWSGINewRelicStatsGenerator
report_metrics (stderr) | ModuleNotFoundError: No module named 'viahtml'
```
To test:
* `make docker`
* `make run-docker`
If you want to actually test the metrics you will need to: `export NEW_RELIC_LICENSE_KEY=<your key here>`
> Set the python path so the metrics script can find `viahtml`

- tests/unit/viahtml/stats_test.py
- viahtml/stats.py
There doesn't appear to be a list of metrics that New Relic understands, but some values clearly have a special meaning. "ms" for instance seems to be understood correctly.
The docs have examples which mention "kilobytes" as the unit, so maybe it is? https://docs.newrelic.com/docs/plugins/plugin-developer-resources/developer-reference/metric-data-plugin-api
Maybe it's just an example? Wouldn't life be boring if they spelled out exactly how this worked? No. No it wouldn't. This is boring.
----
Edit: Which is flatly contradicted here: https://docs.newrelic.com/docs/plugins/plugin-developer-resources/developer-reference/plugin-data#metric_unit_conversions
Which has it as "kiloBytes", but perhaps it's case insensitive. Who knows? It is however 1000, not 1024 bytes.
> Try kilobytes instead of kB to see if New Relic understands

- tests/unit/viahtml/stats_test.py
- viahtml/stats.py
* Changed "ListenQueue", "Socket/Queue" and "SignalQueue" to all be "Queue/*"
* Moved "Worker/Killed" to "Worker/Count/Killed"
* Added "Worker/Count/Idle" and  "Worker/Count/Cheap"
This should all facilitate adding more things to single graphs.
There are a couple of motivations for this:
* The queues don't seem to show much, so they might as well be boring together
* The "accepting" doesn't actually mean it's consuming any resources so the distinction between "idle" and "cheap" matters for estimating actual resource consumption
* e.g. We show 32 workers "accepting" all the time but the memory varies wildly. This is because some "accepting" workers are "cheap"'ed and don't do anything or use any resources
> Changed metric names to nest better and added more

- conf/development.ini
- conf/uwsgi/t3_small.ini
I was initiall setting the dev settings to be the same as live, but we have
to run many services locally, and some people might not have that much RAM
to play with. It's also just not necessary locally.
> Change the T3 to use more memory and the dev to use less

- conf/nginx/nginx.conf
This branch delivers an update to `nginx.conf`. The access_log for the nginx
service running inside our Docker container has been turned off. This brings
the configuration in line with our other applications and stops us sending duplicate
information to Paperrtail.
> Config Update - nginx.conf

- conf/blocklist-dev.txt
- tests/unit/blocklist_test.py
- viahtml/blocklist.py
* This also added some helper functions
* This meant the tests weren't tinking with the guts of the object any more
* Run `make dev`
* Observe that `*.example.edu` is in `conf/blocklist-dev.txt`
* Goto: http://localhost:9085/http://anything.example.edu
* You should see the block page
> Add the ability to use wildcards in the blocklist

- requirements/build.txt
- requirements/dev.txt
- requirements/functests.txt
- requirements/lint.txt
- requirements/requirements.txt
- requirements/tests.txt
I used `hdev requirements --package h-vialib`
Version 1.0.17 whitelists the `ignoreOtherConfiguration` so it can
disregard other hypothesis configurations included in the host page.
> Upgrade to h-vialib version 1.0.17

- Jenkinsfile
The ViaHTML Jenkinsfile contains a step with a sleep 2 command. This
commit removes the 2 second pause to test what happens without it.
> Deployment workflow testing

- bin/build_static.py
This matches all .js files currently present on pywb/static
Currently broken after merging: https://github.com/hypothesis/viahtml/pull/228
* `make build`
* 'tis broken
> Don't try to include JS no longer present in pywb

- tests/unit/viahtml/context_test.py
- tests/unit/viahtml/hooks/hooks_test.py
- viahtml/context.py
- viahtml/hooks/hooks.py
For:
* https://github.com/hypothesis/product-backlog/issues/1307
* https://github.com/hypothesis/viahtml/issues/297
This is part of work to allow local navigation about a page, but not if it goes off of the page. Currently the PR only address the rewriting portion, and means the plan fragment only urls like `#anchor` remain as is.
A the moment there is also a Javascript portion that will need to be addressed which cases the link to pop open into a new tab.
* Start Via and ViaHTML
* Visit http://localhost:9083
* Type in the following address: https://jeffreycwitt.com/pl339/docs/02-the-medium-is-the-message.html
* Inspect the links in the table of contents using F12
* They should be plain anchors (in main they are rewritten)
> Allow fragment only URLs to remain as is on a page

- viahtml/templates/banner.html
The frontend has logic to detect whether a link that is clicked on is an internal or external one, in order to make external links open in a new tab. Following browser behavior (see link in code comments) this involves comparing a link's URL against the current page, ignoring the fragment.
This logic was broken in the current version of wombat/pywb. The approach used to get the proxied URL of the current page did not work due to a bug in pywb/wombat (see commit message for details). This PR uses a different approach that should be more robust.
In addition there was an issue where `via.`-prefixed query parameters are stripped from the URL that pywb receives on the backend to proxy, but are still visible to parts of the pywb frontend JavaScript. When comparing a link's target URL (obtained …
> Fix fragment links being treated as external links (client side)

- requirements/build.txt
- requirements/dev.txt
- requirements/functests.txt
- requirements/lint.txt
- requirements/requirements.txt
- requirements/tests.txt
- tests/functional/conftest.py
- tests/functional/fixups_test.py
- tests/functional/proxy_test.py
- tests/simple_server.py
- tests/unit/viahtml/views/security_test.py
- viahtml/stats.py
- viahtml/views/security.py
Needs:
* https://github.com/hypothesis/checkmatelib/pull/21
This is some ugly error representation, but it's better than burying them. In general you shouldn't be able to get here without having made a mistake somewhere else.
At the moment it's quite hard to get `checkmatelib` to raise, so I'd suggest manually bodging `viahtml/views/security.py` to raise an error:
```python
def __call__(self, context):
...
try:
raise BadURL("TERRIBLE NEWS!")
blocked = self._is_blocked(
context.proxied_url,
context.query_params.get("via.blocked_for"),
allow_all,
)
except BadURL as exc:
return context.make_response(
...
```
* Then start `via` and `viahthml` with `make dev`
* Visit: http://localhost:9083
* Type in any website
* You should see a pretty plain error page
> Catch `BadURL` errors from Checkmate and present them as a 400

- Jenkinsfile
- tests/.pylintrc
1. Replaced the onlyOnMaster function with onlyOnMain in the Jenkinsfile
2. Replace reference to the master branch with main in tests/.pylintrc
> Renamed default branch to main

- requirements/build.in
- requirements/build.txt
- requirements/checkformatting.in
- requirements/checkformatting.txt
- requirements/coverage.in
- requirements/coverage.txt
- requirements/dev.in
- requirements/dev.txt
- requirements/format.in
- requirements/format.txt
- requirements/functests.in
- requirements/functests.txt
- requirements/lint.in
- requirements/lint.txt
- requirements/tests.in
- requirements/tests.txt
- tox.ini
**Developers will have to `rm -rf .tox` in their dev envs after merging this** if they see `command not found: pip-sync-faster`.
Simplify our development tooling by removing the `tox-pip-sync` plugin in favour of calling [`pip-sync-faster`](https://github.com/hypothesis/pip-sync-faster) directly from `tox.ini`.
Also add the [`tox-faster`](https://github.com/hypothesis/tox-faster) plugin to `tox.ini`: `tox-faster` is a standalone implementation of a small `tox` speedup that was previously implemented in `tox-pip-sync`.
We did this in LMS a while ago and haven't noticed any problems there:
https://github.com/hypothesis/lms/pull/4191/files
Details
-------
* `pip-sync-faster` is added to all the `requirements/*.in` files (except the production `requirements/requirements.in`). …
> Remove `tox-pip-sync`

- requirements/dev.txt
- requirements/functests.txt
- requirements/lint.txt
- requirements/requirements.in
- requirements/requirements.txt
- requirements/tests.txt
`h-checkmatelib` has been renamed to just `checkmatelib`:
hypothesis/checkmatelib#24
This commit is the result of replace `h-checkmatelib` with `checkmatelib` in `requirements.in` and then running `make requirements`.
> Replace `h-checkmatelib` with just `checkmatelib`

- requirements/build.txt
- requirements/dev.txt
- requirements/functests.txt
- requirements/lint.txt
- requirements/requirements.txt
- requirements/tests.txt
Upgrade the `cryptography` and `pyopenssl` packages to their latest
versions by running:
make requirements --always-make args='--upgrade-package cryptography --upgrade-package pyopenssl'
When trying to run Via HTML on a Mac with Apple Silicon it's crashing
when trying to compile the ancient version of `cryptography` that Via
HTML depends on:
fatal error: 'openssl/opensslv.h' file not found
I think `cryptography` publish pre-compiled binary wheels for Apple
Silicon so `pip` shouldn't need to compile it. I suspect that the old
version of `cryptography` has no Apple Silicon pre-compiled binary so
that's why it's trying to compile it.
Fix this by upgrading `cryptography` to the latest version.
Also upgrade `pyopenssl` at the same time, otherwise the tests fail
because the old version of …
> Upgrade `cryptography` and `pyopenssl`

- .github/workflows/deploy.yml
I think this might make GitHub Actions's visualisation of the deployment
jobs look better, but I suspect it may actually just break the workflow.
> Tweak deployment job dependencies

- .github/workflows/deploy.yml
For QA and production Via HTML use direct URLs for proxying an HTML
page.
For QA and production Via HTML (Edu) use links to HTML test assignments
from our test Canvas instance. (You can't use Via HTML (Edu) directly,
you have to go through the LMS app.)
> Use better GitHub environment URLs

- viahtml/templates/banner.html
When external links are configured to open in a new tab, prevent any of the page's own event handlers for those links from running, in case they try to do a client-side navigation. GitBook for example does this with links in the sidebar.
Fixes https://github.com/hypothesis/viahtml/issues/423
> Prevent click handlers on external links from running

- tests/unit/viahtml/hooks/hooks_test.py
- viahtml/hooks/hooks.py
For:
* https://github.com/hypothesis/lms/issues/4697
We include our own canonical link in the header, but if the document includes one `pywb` was rewriting it to be a link pointing to Via. This caused annotations to get lost.
* Is there any problem with allowing a document to declare it's own Canonical URL?
* Start Via and ViaHTML
* Visit: http://localhost:9083/https://www.ascd.org/el/articles/6-intrinsic-motivators-to-power-up-your-teaching
* Open dev tools
* Filter by `openSidebar`
* Look at the HTML response and search for `canonical`
* You should see our canonical URL added with ``
* You should find another one added by the original document
Depending on branch:
* In `main` - The URL is rewritten to include Via information
* In this branch - The URL is the original document URL
> Prevent pywb from rewriting links with `rel=canonical`

- Makefile
- bin/build_static.py
Copy all resources instead of a specific list of files.
This fixes an issue where Docker builds failed after the latest pywb 2.6.7 => 2.7.3 upgrade due to one of the files no longer being present in the pywb package. More generally this makes pywb version upgrades easier by not requiring this script to be updated as often when updating pywb versions, at the cost of also including some files we don't actually need.
On a related note, it seems that CI builds don't verify that Docker builds work. This will be fixed separately.
To verify:
1. Check out this branch
2. Run `make docker`
3. Run `docker create docker.io/hypothesis/viahtml:dev` to create a container but not start it. This will print out a container ID.
4. Run `docker export <container ID> > viahtml.tar` to export container …
> Copy all static resources from pywb/static/ to Docker image

- tests/functional/conftest.py
- tests/functional/proxy_test.py
- tests/unit/viahtml/hooks/hooks_test.py
- tox.ini
- viahtml/hooks/hooks.py
Allow a page to have iframes that remain unproxied when the data-h-no-proxy attribute is set.
Resolves hypothesis/viahtml#457
> Allow hint in iframe to bypass proxy

- tox.ini
Some of our dependencies use the deprecated pkg_resources API.
Ignoring the warning until they get updated.
> Add a filter warning for pkg_resources deprecation

- requirements/build.txt
- requirements/dev.txt
- requirements/functests.txt
- requirements/lint.txt
- requirements/requirements.txt
- requirements/tests.txt
This reverts commit 3d2d08d714a63f3622406607b55a85569f5b09f2.
New version of Cpython make pyyaml to fail to build but the version we use is pinned by docker-compose v1 which is itself deprecated and won't be updated.
https://github.com/yaml/pyyaml/issues/601
https://github.com/docker/compose/issues/10836
Reverting this to have a deployable version on main.
> Revert "Bump certifi from 2022.12.7 to 2023.7.22"

- Makefile
- conf/supervisord-dev.conf
- requirements/dev.in
- requirements/dev.txt
Rely instead on the go version of docker (which now includes composer).
The python version of docker-compose is no longer supported and it has pinned dependencies to old packages that are holding back security upgrades of other packages.
Just try `make dev` on local
> Remove docker-compose dependency

- .github/workflows/ci.yml
Re-run `ci.yml` on `main` after merging a PR (or after pushing commits
directly to `main`). This is necessary for two reasons:
1. It updates GitHub Actions caches on `main` (which can be read from
any PR branches), which saves time re-installing dependencies on PRs
2. It will send us a Slack notification if CI fails on `main`
This will enable us to remove the `ci.yml` call from `deploy.yml`.
> Run `ci.yml` after any push to `main`

- tests/unit/viahtml/hooks/hooks_test.py
- viahtml/hooks/hooks.py
YouTube was originally blocked in Via because proxying the video content is resource intensive, and people were using Via as a way of getting around content blocking at work/school etc. However we don't want to really want to block this content when it appears as an embed, we just want to avoid proxying it.
This commit adds the prefixes of several popular embedded video players to the existing allowlist that we use to prevent Via from proxying the Hypothesis client's iframe/scripts/styles. A downside of this approach is that we have to individually add new video players as we encounter them. A broader approach might be to try and avoid proxying iframes altogether, but that is a riskier change.
An alternative approach would be to make the policy of whether to proxy or not part of …
> Disable proxying for several popular embedded video players

- requirements/build.txt
- requirements/checkformatting.txt
- requirements/coverage.txt
- requirements/dev.txt
- requirements/format.txt
- requirements/functests.txt
- requirements/lint.txt
- requirements/requirements.txt
- requirements/tests.txt
This is the result of running:
make requirements --always-make args='--upgrade'
Non top level dependencies can become outdated as dependabot doesn't send PR for those.
On top of that upgrading single packages with all the existing constraints might make impassible to satisfy all constraints.
This approach makes sure we are up to date with all our dependencies as specified on the .in files but without considering any constraints in the .txt files
> Upgrade python dependencies

- tests/unit/viahtml/context_test.py
- tests/unit/viahtml/hooks/hooks_test.py
- viahtml/context.py
- viahtml/hooks/hooks.py
- viahtml/patch.py
This PR adds support for disabling proxying of iframes on a per-request basis by adding a `via.proxy_iframes=0` query param to the Via URL.
The downside of not proxying iframes is that the non-proxied frame will become cross-origin with its parent, which will break any JS code that assumes it can reach from the parent into the frame, or vice-versa.
Ideally we would avoid proxying frames by default in Via, since it would save resources on our side (less content to proxy), and make any content in the iframes load faster. However because there is some compatibility risk (ie. breaking sites that used to work), we'll need to roll this change out incrementally. The initial use case is https://github.com/hypothesis/lms/pull/6045.
Part of https://github.com/hypothesis/support/issues/98.
> Support disabling proxying of iframes on a per-request basis via `via.proxy_frames` query param

- Dockerfile
The fix here matches the Dockerfile in h.
> Fix Docker build after switch to Python 3.11

- conf/production.ini
- conf/uwsgi/t3_medium.ini
In production workers have a typical RSS of ~90MB, but of that only 45-50MB is private to the process. With the previous RSS limits, production was effectively capped at 17 workers (1536 / 90 ~= 17). Additionally the configuration assumed 2GB memory per host, but the configuration was subsequently changed to use t3.medium with 4GB.
This commit raises the cap on the number of workers and removes the fixed memory limits, which were outdated. This should allow the service to scale up workers better to meet bursts of demand.
See https://github.com/hypothesis/viahtml/issues/696
> Revise worker and memory usage limits for uWSGI workers

- Dockerfile
gevent is used by both uWSGI and pywb. pywb pins it to v22.10.2. However there have been fixes for the version of Python we are using in v24.2.1. In order to test whether the older version of gevent is responsible for hangs we are seeing in production, update gevent in the Docker container.
Testing:
- Build docker container locally with `make docker`
- Run viahtml container with `make run-docker`
- Run the local _via_ service using `make dev`, and check that you can browse to http://localhost:9083/https://example.org/
See also:
- [gevent changelog](https://www.gevent.org/changelog.html)
- [Slack thread](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1726476148088089?thread_ts=1726470138.505809&cid=C4K6M7P5E)
> Add a temporary hack to upgrade gevent and greenlet in Docker

- viahtml/wsgi.py
To help debug cases where a worker process "hangs", add a SIGCONT signal handler which dumps both the native and greenlet threads.
**Testing:**
1. Run `make dev`
2. Find pid of a uwsgi worker by running `ps aux | grep uwsgi`
3. Send signal to uwsgi worker using `kill -s SIGCONT $PID`
This will cause native and greenlet stack traces to be dumped to the worker's stderr.
> Support dumping gevent stacks from uWSGI workers

- requirements/dev.txt
- requirements/functests.txt
- requirements/lint.txt
- requirements/requirements.in
- requirements/requirements.txt
- requirements/tests.txt
urllib3 v1.26.16 was reported by some GitHub users as encountering deadlocks in gevent. Pin to an earlier version to test whether this makes a difference in our case.
See comments in https://github.com/gevent/gevent/issues/1957 and https://github.com/urllib3/urllib3/issues/3289.
Slack investigation: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1726591090893969?thread_ts=1726470138.505809&cid=C4K6M7P5E
urllib3 changelog: https://github.com/urllib3/urllib3/blob/main/CHANGES.rst#12616-2023-05-23
> Pin urllib3 to v1.26.15

- .github/dependabot.yml
- requirements/requirements.in
urllib3 is pinned until an issue between later versions and urllib3 is resolved.
> Stop Dependabot from updating urllib3

- .coveragerc
- viahtml/_version.py
- viahtml/wsgi.py
The releases feature is useful in itself, and this should also stop the
"discarded session update because of missing release" messages that
`sentry_sdk` is logging all the time.
> Enable Sentry's "releases" feature
